'use strict';
const { Model } = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class Rentals extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // Rental belongs to ONE User (agent/owner)
      Rentals.belongsTo(models.Users, {
        foreignKey: "UserId",
        // as: 'agent'
      });
    }
  }


  Rentals.init({
    title: DataTypes.STRING,
    description: DataTypes.TEXT,
    UserId: DataTypes.UUID,
    likesCount: DataTypes.INTEGER,
    propertyType: DataTypes.ENUM('apartment', 'house', 'office', 'commercial', 'land'),
    location: DataTypes.STRING,
    price: DataTypes.DECIMAL(12, 2),
    priceType: DataTypes.ENUM('monthly', 'yearly', 'one-time'),
    images: DataTypes.JSON,
    videos: DataTypes.JSON,
    status: DataTypes.ENUM('available', 'rented', 'pending'),
    slug: {
      type: DataTypes.STRING,
      unique: true
    }
  }, {
    sequelize,
    modelName: 'Rentals',
    tableName: 'rentals',
    timestamps: true,
    hooks: {
      beforeCreate: async (rental) => {
        const slugify = require('../utils/slugify');
        if (rental.title) {
          let slug = slugify(rental.title);
          // Check for collision
          const existing = await rental.constructor.findOne({ where: { slug } });
          if (existing) {
             // Use part of UUID if available, or generate a random one if it's new and doesn't have ID yet
             // Actually, rentals usually have a UUID generated by DB or Sequelize.
             // If not yet present, we can use a random short string.
             const suffix = rental.id ? rental.id.split('-')[0] : Math.random().toString(36).substring(2, 6);
             slug = slugify(rental.title, suffix);
          }
          rental.slug = slug;
        }
      },
      beforeUpdate: async (rental) => {
        const slugify = require('../utils/slugify');
        if (rental.changed('title')) {
          let slug = slugify(rental.title);
          const existing = await rental.constructor.findOne({ where: { slug, id: { [require('sequelize').Op.ne]: rental.id } } });
          if (existing) {
             slug = slugify(rental.title, rental.id.split('-')[0]);
          }
          rental.slug = slug;
        }
      }
    }
  });
  
  return Rentals;
};